import {dimensions,adjectives,tripDNA,parseAdjustment} from './engine.js';
import {places,defaultPlaceIds,mapUrl} from './catalog.js';
import {buildOfflineDay,distanceKm,recommendRouteChoices} from './offline-planner.js';
import {groupRouteCost} from './budget.js';

const $=id=>document.getElementById(id);
const node=(tag,cls='',value='')=>{const el=document.createElement(tag);el.className=cls;el.textContent=value;return el;};
const selectedWords=new Set(),key='trip-planner-offline-v3';
let trip=null,activeDay=0,changes=[],choices=[];
function save(){if(trip)try{sessionStorage.setItem(key,JSON.stringify({trip,activeDay,changes,choices,words:[...selectedWords]}));}catch{}}
function show(id){for(const name of ['feel','conditions','result'])$(name).classList.toggle('hidden',name!==id);['feel','conditions','result'].forEach((name,i)=>$(`step${i+1}`).classList.toggle('active',name===id));window.scrollTo(0,0);}
for(const word of Object.keys(adjectives)){const b=node('button','chip',word);b.type='button';b.setAttribute('aria-pressed','false');b.onclick=()=>{selectedWords.has(word)?selectedWords.delete(word):selectedWords.add(word);b.setAttribute('aria-pressed',String(selectedWords.has(word)));renderDNA();};$('chips').append(b);}
function renderDNA(){const box=$('dnaBars');box.replaceChildren();for(const [id,label] of Object.entries(dimensions)){const value=tripDNA(selectedWords).weights[id],row=node('div','barrow'),track=node('div','track'),fill=node('div','fill');fill.style.width=`${value}%`;track.append(fill);row.append(node('span','',label),track,node('strong','',String(value)));box.append(row);}}
const choiceBox=$('placeChoices');let area='';for(const place of places){if(place.area!==area){area=place.area;choiceBox.append(node('h3','place-area',area));}const label=node('label','place-choice'),input=node('input');input.type='checkbox';input.value=place.id;input.checked=defaultPlaceIds.includes(place.id);label.append(input,node('span','',`${place.name} · ${place.kind==='indoor'?'室內':'戶外'} · 約 ${place.minutes} 分`));choiceBox.append(label);}
function selectedIds(){return [...choiceBox.querySelectorAll('input:checked')].map(x=>x.value);}
function setIds(ids){for(const input of choiceBox.querySelectorAll('input'))input.checked=ids.includes(input.value);}
const tomorrow=new Date(Date.now()+86400000);$('date').value=`${tomorrow.getFullYear()}-${String(tomorrow.getMonth()+1).padStart(2,'0')}-${String(tomorrow.getDate()).padStart(2,'0')}`;
$('days').value='3';
$('next').onclick=()=>show('conditions');$('back').onclick=()=>show('feel');$('editTrip').onclick=()=>show('conditions');$('restart').onclick=()=>{trip=null;sessionStorage.removeItem(key);show('feel');};
function dateFor(i){const d=new Date(`${trip.date}T12:00:00`);d.setDate(d.getDate()+i);return `${d.getMonth()+1}/${d.getDate()}`;}
function clock(minutes){return `${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;}
function day(i){return buildOfflineDay(i,trip,tripDNA(selectedWords),changes[i]);}
function chooseRoutes(d){return recommendRouteChoices(d,trip.travelers,tripDNA(selectedWords),trip.budget).choices;}
function updateSummary(){$('resultTitle').textContent=`釜山 · ${trip.date} 起 ${trip.days} 天`;$('summary').textContent=`${trip.travelers} 人 · ${trip.placeIds.length} 個所選地點 · 每日全團交通預算 ${trip.budget.toLocaleString()} KRW · 偏好：${[...selectedWords].join('、')||'均衡'}`;}
$('tripForm').onsubmit=e=>{e.preventDefault();$('formError').textContent='';if(!e.currentTarget.reportValidity())return;const destination=$('destination').value.trim();if(!/^(釜山|busan)$/i.test(destination)){$('formError').textContent='目前只有釜山具名離線地點，無法為其他目的地編造行程。';return;}const ids=selectedIds(),days=Number($('days').value);if(ids.length<days){$('formError').textContent=`已選 ${ids.length} 個地點，${days} 天至少需選 ${days} 個。`;return;}if(ids.length>days*4){$('formError').textContent=`為保留旅行節奏，每天最多安排 4 個地點；${days} 天請選不超過 ${days*4} 個。`;return;}
  trip={destination:'釜山',date:$('date').value,days,travelers:Number($('travelers').value),budget:Number($('budget').value),placeIds:ids};activeDay=0;changes=Array.from({length:days},()=>({}));choices=Array.from({length:days},(_,i)=>chooseRoutes(day(i)));updateSummary();render();save();show('result');};
function renderTabs(){const box=$('dayTabs');box.replaceChildren();for(let i=0;i<trip.days;i++){const b=node('button','day-tab',`第 ${i+1} 天 · ${dateFor(i)}`);b.type='button';b.setAttribute('aria-pressed',String(i===activeDay));b.onclick=()=>{activeDay=i;$('preview').replaceChildren();render();save();};box.append(b);}}
function render(){renderTabs();const d=day(activeDay),box=$('schedule');box.replaceChildren();box.append(node('h3','',`第 ${activeDay+1} 天 · ${d.title}`));const all=Array.from({length:trip.days},(_,i)=>day(i));const today=d.legs.reduce((sum,leg,i)=>sum+groupRouteCost(leg.options[choices[activeDay]?.[i]??0],trip.travelers),0);const whole=all.reduce((sum,item,j)=>sum+item.legs.reduce((s,leg,i)=>s+groupRouteCost(leg.options[choices[j]?.[i]??0],trip.travelers),0),0);
  const budget=node('div',`budget-card${today>trip.budget?' over-budget':''}`);budget.append(node('strong','',`當日交通粗估 ${today.toLocaleString()} / ${trip.budget.toLocaleString()} KRW`),node('p','',`全程交通粗估 ${whole.toLocaleString()} KRW。這不是報價，且不含住宿、餐食與景點費。`));box.append(budget);
  let cursor=600;d.stops.forEach((stop,i)=>{const card=node('article','stop');card.append(node('time','',`建議 ${clock(cursor)}`),node('h3','',stop.name),node('p','',`${stop.kind==='indoor'?'室內':'戶外'} · 建議停留約 ${stop.minutes} 分 · ${stop.note}`));const map=node('a','map-link','查看地圖 ↗');map.href=mapUrl(stop);map.target='_blank';map.rel='noopener noreferrer';card.append(map);if(stop.rainReplacement)card.append(node('p','hint','已替換為附近未排入的室內地點'));box.append(card);
    const leg=d.legs[i];if(!leg)return;const section=node('section','leg');section.append(node('h4','',`前往 ${d.stops[i+1].name} · 約 ${distanceKm(stop,d.stops[i+1]).toFixed(1)} km 直線距離`));section.append(node('p','hint','以下時間、票價與體力為離線估算；實際道路與班次請用地圖查證。'));const list=node('div','route-list');leg.options.forEach((route,j)=>{const label=node('label',`route-option${(choices[activeDay]?.[i]??0)===j?' selected':''}`),radio=node('input');radio.type='radio';radio.name=`route-${activeDay}-${i}`;radio.checked=(choices[activeDay]?.[i]??0)===j;radio.onchange=()=>{choices[activeDay][i]=j;render();save();};const info=node('span','route-body');info.append(node('strong','',`${route.mode} · 約 ${route.duration_min} 分`),node('small','',`Money ${groupRouteCost(route,trip.travelers).toLocaleString()} KRW／團 · Time ${route.duration_min} 分`),node('small','',`Energy ${route.energy_score}/100 · Friction ${route.friction_score}/100 · 步行約 ${route.walking_min} 分`));label.append(radio,info);list.append(label);});section.append(list);const directions=node('a','map-link','查詢這段實際路線 ↗');directions.href=`https://www.google.com/maps/dir/?api=1&origin=${stop.lat}%2C${stop.lng}&destination=${d.stops[i+1].lat}%2C${d.stops[i+1].lng}`;directions.target='_blank';directions.rel='noopener noreferrer';section.append(directions);box.append(section);cursor+=stop.minutes+30+leg.options[choices[activeDay]?.[i]??0].duration_min;});}
$('adjustForm').onsubmit=e=>{e.preventDefault();const intent=parseAdjustment($('adjust').value),preview=$('preview');preview.replaceChildren();if(!intent.tired&&!intent.rain&&!intent.noMetro){preview.append(node('p','error','目前只理解「累了／少走路」、「下雨」、「不搭地鐵」。'));return;}const description=[intent.tired?'刪除當日最後一站並移除純步行選項':null,intent.rain?'嘗試將當日戶外點替換為未使用的附近室內點':null,intent.noMetro?'目前離線交通沒有地鐵資料，行程不變':null].filter(Boolean).join('；');preview.append(node('p','preview',description));const apply=node('button','primary','套用到這一天');apply.type='button';apply.onclick=()=>{changes[activeDay]={...changes[activeDay],...intent};choices[activeDay]=chooseRoutes(day(activeDay));render();save();preview.replaceChildren(node('p','preview','已套用；可繼續切換其他日期。'));};preview.append(apply);};
renderDNA();try{const saved=JSON.parse(sessionStorage.getItem(key));if(saved?.trip?.placeIds?.length&&saved.trip.days>=1&&saved.trip.days<=6&&/^(釜山|busan)$/i.test(saved.trip.destination)){trip=saved.trip;activeDay=Math.min(saved.activeDay||0,trip.days-1);changes=saved.changes||Array.from({length:trip.days},()=>({}));choices=saved.choices||Array.from({length:trip.days},()=>[]);for(const word of saved.words||[])if(Object.hasOwn(adjectives,word))selectedWords.add(word);for(const chip of $('chips').children)chip.setAttribute('aria-pressed',String(selectedWords.has(chip.textContent)));for(const id of ['destination','date','days','travelers','budget'])$(id).value=trip[id];setIds(trip.placeIds);renderDNA();updateSummary();render();show('result');}}catch{}
