import {dimensions,adjectives,tripDNA,createDay,parseAdjustment} from './engine.js';
import {summarizeDayTransport} from './budget.js';
const $=id=>document.getElementById(id);const selected=new Set();let input,day,adjustment={};
function el(tag,cls,content){const node=document.createElement(tag);if(cls)node.className=cls;if(content!=null)node.textContent=content;return node;}
for(const word of Object.keys(adjectives)){const b=el('button','chip',word);b.type='button';b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{selected.has(word)?selected.delete(word):selected.add(word);b.setAttribute('aria-pressed',String(selected.has(word)));renderDNA();});$('chips').append(b);}
function renderDNA(){const box=$('dnaBars');box.replaceChildren();const dna=tripDNA(selected);for(const [key,label] of Object.entries(dimensions)){const row=el('div','barrow');row.append(el('span','',label));const track=el('div','track'),fill=el('div','fill');fill.style.width=`${dna.weights[key]}%`;track.append(fill);row.append(track,el('strong','',String(dna.weights[key])));box.append(row);}}
function show(name){for(const id of ['feel','conditions','result'])$(id).classList.toggle('hidden',id!==name);['step1','step2','step3'].forEach((id,i)=>$(id).classList.toggle('active',['feel','conditions','result'][i]===name));window.scrollTo(0,0);}
$('next').addEventListener('click',()=>show('conditions'));$('back').addEventListener('click',()=>show('feel'));$('restart').addEventListener('click',()=>show('feel'));
const tomorrow=new Date(Date.now()+86400000);$('date').value=[tomorrow.getFullYear(),String(tomorrow.getMonth()+1).padStart(2,'0'),String(tomorrow.getDate()).padStart(2,'0')].join('-');
$('tripForm').addEventListener('submit',e=>{e.preventDefault();input={destination:$('destination').value.trim(),date:$('date').value,days:Number($('days').value),travelers:Number($('travelers').value),budget:Number($('budget').value)};if(!input.destination||!input.date||input.days<1||input.travelers<1)return;adjustment={};day=createDay(input,tripDNA(selected));renderDay();show('result');});
function optionNode(o,best){const box=el('div','option');box.append(el('strong','',`${best?'推薦 · ':''}${o.mode} · ${o.duration_min} 分鐘`));const costs=el('div','costs');const money=o.estimated_cost*(o.mode==='計程車'?1:input.travelers);for(const s of [`Money ${money.toLocaleString()} ${o.currency}/團`,`Time ${o.duration_min} 分`,`Energy ${o.energy_score}/100`,`Friction ${o.friction_score}/100`])costs.append(el('span','',s));box.append(costs,el('div','hint',`步行 ${o.walking_min} 分 · 轉乘 ${o.transfers} 次`));return box;}
function renderDay(){const box=$('schedule');box.replaceChildren();$('resultTitle').textContent=`${input.destination} · ${input.date} 起 ${input.days} 天`;$('summary').textContent=`${input.travelers} 人 · 每日交通預算 ${input.budget.toLocaleString()} KRW（全團） · 選擇：${[...selected].join('、')||'預設均衡'}。目前只展示第 1 天${input.destination==='釜山'?'':'的釜山範例，並非該目的地真實行程'}。`;
 const transport=summarizeDayTransport(day,input.travelers,input.budget);const budgetCard=el('div',`budget-card${transport.withinBudget?'':' over-budget'}`);budgetCard.append(el('strong','',`第 1 天推薦交通估算：${transport.total.toLocaleString()} KRW／團`),el('p','',transport.withinBudget?`比設定上限少 ${transport.difference.toLocaleString()} KRW`:`超過設定上限 ${(-transport.difference).toLocaleString()} KRW；請查看其他交通方案。`));box.append(budgetCard);
 day.stops.forEach((stop,i)=>{const card=el('article','stop');card.append(el('time','',stop.time),el('h3','',stop.name),el('p','',`${stop.priority} · ${stop.note}`));box.append(card);if(i>=day.legs.length)return;const leg=day.legs[i],wrap=el('div','leg');wrap.append(el('strong','',`前往下一站 · ${leg.options[0].mode}`),optionNode(leg.options[0],true));if(leg.options.length>1){const more=el('details');more.append(el('summary','',`查看其他 ${leg.options.length-1} 種交通`));for(const o of leg.options.slice(1))more.append(optionNode(o,false));wrap.append(more);}box.append(wrap);});}
$('adjustForm').addEventListener('submit',e=>{e.preventDefault();const next=parseAdjustment($('adjust').value);const preview=$('preview');preview.replaceChildren();if(!Object.values(next).some(Boolean)){preview.append(el('p','error','此版尚無法理解這句話。請試「累了」、「下雨」或「不搭地鐵」。'));return;}const effects=[next.tired?'縮短步行並移除可取消的咖啡站':null,next.rain?'以室內示範站替換戶外散步':null,next.noMetro?'移除地鐵選項':null].filter(Boolean);preview.append(el('p','preview',`預覽影響：${effects.join('；')}。這是 mock 規則，未驗證營業、訂位或路線。`));const apply=el('button','primary','套用示範調整');apply.type='button';apply.addEventListener('click',()=>{adjustment={...adjustment,...next};day=createDay(input,tripDNA(selected),adjustment);renderDay();preview.replaceChildren(el('p','preview','已套用示範調整；請再次確認實際資訊。'));});preview.append(apply);});
renderDNA();
