// Pure mock engine. Future adapters should return the same Place, RouteOption and Day shapes.
export const dimensions = {pace:'緊湊度',comfort:'舒適需求',exploration:'探索程度',tourist_density:'熱門景點接受度',transport_tolerance:'轉乘接受度',walking_tolerance:'步行接受度',food_priority:'美食優先',hotel_priority:'住宿優先',budget_sensitivity:'價格敏感度',flexibility:'彈性需求'};
export const adjectives = {
  '舒服':{comfort:30,pace:-15,walking_tolerance:-15},'隨性':{flexibility:35,pace:-15},'緊湊':{pace:35,flexibility:-15},'深度':{exploration:25,tourist_density:-20},
  '在地':{exploration:25,tourist_density:-25,food_priority:10},'精緻':{comfort:20,hotel_priority:25,budget_sensitivity:-15},'療癒':{comfort:25,pace:-25},
  '探索':{exploration:35,walking_tolerance:10},'浪漫':{comfort:15,hotel_priority:15},'親子':{comfort:25,pace:-15,walking_tolerance:-15},
  '美食':{food_priority:40},'購物':{flexibility:10,pace:10},'自然':{exploration:20,tourist_density:-10},'城市':{transport_tolerance:10},
  '夜生活':{pace:10,flexibility:15},'高 CP 值':{budget_sensitivity:35},'不想早起':{pace:-20,flexibility:15},
  '不喜歡排隊':{tourist_density:-25,comfort:10},'少走路':{walking_tolerance:-35,comfort:10},'不要過度觀光':{tourist_density:-35,exploration:15},'不想一直換交通工具':{transport_tolerance:-35,comfort:10}
};
export function tripDNA(words){const dna=Object.fromEntries(Object.keys(dimensions).map(k=>[k,50]));for(const word of words)for(const [key,delta] of Object.entries(adjectives[word]||{}))dna[key]=Math.max(0,Math.min(100,dna[key]+delta));return {weights:dna,rawAdjectives:[...words]};}
export const mockPlaces=[{id:'station',name:'釜山站附近',time:'10:00',note:'集合與緩慢開始',priority:'必去'},{id:'market',name:'草梁故事路',time:'11:00',note:'同區散步，保留彈性休息',priority:'高優先'},{id:'lunch',name:'在地午餐示範點',time:'12:30',note:'請自行查核營業與飲食限制',priority:'高優先'},{id:'cafe',name:'港景咖啡休息',time:'14:30',note:'留白與休息時間',priority:'可取消'}];
export const mockRoutes={
  'station-market':[{mode:'步行',duration_min:18,estimated_cost:0,currency:'KRW',walking_min:18,transfers:0,energy_score:42,friction_score:8},{mode:'公車',duration_min:15,estimated_cost:1500,currency:'KRW',walking_min:5,transfers:0,energy_score:15,friction_score:24},{mode:'計程車',duration_min:9,estimated_cost:6500,currency:'KRW',walking_min:2,transfers:0,energy_score:5,friction_score:12}],
  'market-lunch':[{mode:'步行',duration_min:12,estimated_cost:0,currency:'KRW',walking_min:12,transfers:0,energy_score:28,friction_score:5},{mode:'公車',duration_min:13,estimated_cost:1500,currency:'KRW',walking_min:4,transfers:0,energy_score:12,friction_score:23},{mode:'計程車',duration_min:7,estimated_cost:5500,currency:'KRW',walking_min:2,transfers:0,energy_score:5,friction_score:11}],
  'lunch-cafe':[{mode:'地鐵',duration_min:22,estimated_cost:1600,currency:'KRW',walking_min:9,transfers:0,energy_score:23,friction_score:21},{mode:'公車',duration_min:27,estimated_cost:1500,currency:'KRW',walking_min:5,transfers:0,energy_score:16,friction_score:28},{mode:'計程車',duration_min:14,estimated_cost:9500,currency:'KRW',walking_min:2,transfers:0,energy_score:6,friction_score:12}]
};
export function routeScore(route,people,dna){const w=dna.weights;const money=(route.estimated_cost*(route.mode==='計程車'?Math.ceil(people/4):people))/Math.max(1,people);return money*(0.018+w.budget_sensitivity/2500)+route.duration_min*(1+w.pace/100)+route.energy_score*(1+(100-w.walking_tolerance)/60)+route.friction_score*(1+(100-w.transport_tolerance)/80);}
export function createDay(input,dna,adjustment={}){const stops=mockPlaces.filter(p=>!(adjustment.rain&&p.id==='market')&&!(adjustment.tired&&p.id==='cafe'));if(adjustment.rain)stops.splice(1,0,{id:'indoor',name:'室內展示空間（示範替代）',time:'11:00',note:'雨天同區替代，請查核實際地點',priority:'可取消'});const legs=[];for(let i=1;i<stops.length;i++){const key=`${stops[i-1].id}-${stops[i].id}`;let options=mockRoutes[key]||mockRoutes['market-lunch'];options=options.filter(o=>!adjustment.noMetro||o.mode!=='地鐵');if(adjustment.tired)options=options.filter(o=>o.walking_min<=9);legs.push({from:stops[i-1].id,to:stops[i].id,options:[...options].sort((a,b)=>routeScore(a,input.travelers,dna)-routeScore(b,input.travelers,dna)).slice(0,3)});}return {stops,legs,mock:true};}
export function parseAdjustment(text){return {tired:/累|少走|不想走|小孩/.test(text),rain:/雨|室內/.test(text),noMetro:/不搭地鐵|不要地鐵|避開地鐵/.test(text)};}
