import assert from 'node:assert/strict';
import {tripDNA,createDay,parseAdjustment,mockRoutes,routeScore} from './engine.js';
import {groupRouteCost,summarizeDayTransport} from './budget.js';
const dna=tripDNA(['舒服','少走路','美食']);
assert.equal(dna.weights.comfort,90);
assert.equal(dna.weights.walking_tolerance,0);
assert.equal(dna.weights.food_priority,90);
assert.deepEqual(dna.rawAdjectives,['舒服','少走路','美食']);
const input={travelers:5};
const day=createDay(input,dna);
assert.ok(day.stops.length>=2);
assert.equal(day.legs.length,day.stops.length-1);
assert.ok(day.legs.every(x=>x.options.length<=3&&x.options.length>0));
assert.ok(day.legs.every(x=>x.options.every((o,i,a)=>!i||routeScore(a[i-1],5,dna)<=routeScore(o,5,dna))));
assert.equal(mockRoutes['station-market'].find(x=>x.mode==='公車').estimated_cost*5,7500);
assert.equal(groupRouteCost(mockRoutes['station-market'].find(x=>x.mode==='計程車'),5),6500);
assert.equal(groupRouteCost(mockRoutes['station-market'].find(x=>x.mode==='公車'),5),7500);
const budget=summarizeDayTransport(day,5,0);
assert.ok(budget.total>=0);
assert.equal(budget.difference,-budget.total);
assert.equal(budget.withinBudget,budget.total===0);
const changes=parseAdjustment('下雨了，不搭地鐵，大家累了');
assert.deepEqual(changes,{tired:true,rain:true,noMetro:true});
const revised=createDay(input,dna,changes);
assert.ok(revised.stops.some(x=>x.id==='indoor'));
assert.ok(revised.legs.every(x=>x.options.every(o=>o.mode!=='地鐵'&&o.walking_min<=9)));
console.log('TripDNA mock engine tests passed');
